config/routes.rb
Rails.application.routes.draw do
  get "pages/about"
  get "pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"
  get "about", to: "pages#about"
  resources :articles

  get "signup", to: "users#new"
  resources :users, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  # associating categoreis and articles table using has_many and has_many: :through
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :description, presence: true, length: { minimum: 3, maximum: 100 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # layout "application"

  # getting user based on params and populating to respective actions
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # if not logged in then only allow show and index actions
  before_action :require_user, except: [:show, :index]
  # if logged in which is based on requrire_user, verfies if the article author and logged in user are same
  before_action :require_same_user, only: [:edit, :update, :destory]

  def show
    @entry_num = params[:id]
  end

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 3)
    @users = User.all
  end

  def new
    # pre populating in order to pass it to template file so that even if entry isn't succesful, we won't get nil error for intance variable
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    # using helper method defined in application_controller to get the current user
    @article.user = current_user

    if @article.save
      # flash is built in ruby method
      # showing flash display on sucesful saving
      flash[:notice] = "Article was created successfully"
      # redirecting to /article/<id>
      redirect_to @article
    else
      # render the new.html.erb page whith list of errors
      flash[:alert] = "Article was not created "
      render "new"
    end
    # show the param data recived from the form
    # render plain: @article.inspect
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article updated successfully"
      redirect_to @article
    else
      flash[:alert] = "couldn't update "
      render "edit"
    end
    @data_received = params[:article]
  end

  def destroy
    if @article.destroy
      flash[:notice] = "deleted id #{params[:id]} entry "
      redirect_to articles_path
    end
  end

  private

  # private method to get theparticular entry based on id
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    #  category_ids is plural insted of category_id since it is many-to-many association
    params.require(:article).permit(:title, :description, category_ids: [])
  end
end

app/views/articles/_articles.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-center last-card-margin ">
      <div class="col-8 mt-4 ">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user  %>
              <p> Created by  <%= link_to article.user.username, user_path(article.user)  %>  </p>
              <p> Article ID: <%= article.id   %>, user ID: <%= article.user.id  %></p>
            <% end  %>
            <%# showing categories %>
            <% if article.categories.any? %>
              <%# if any category is present then, it loops through it and renders through the partial which is expected as _categoy.html.erb %>
              <div class="mt-2"><%= render article.categories %></div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title text-left"> <strong>Title: </strong>  <%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text text-left "> <strong>Description: </strong>  <%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% ## only show edit and delete links if 1) the current user is logged 2) current article is realted to the logged in user   %>
            <% if logged_in? && (article.user == current_user || current_user.admin?)%>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end  %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
              edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_error.html.erb
<%# ! showing error messages  %>
<% if @article.errors.any?  %>
  <h2>Following Errors occoured</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg|  %>
      <li> <%= msg  %> </li>
    <% end  %>
  </ul>
<% end  %>

app/views/articles/_form.html.erb
<%# ! showing error messages  %>
<div class="container">
  <div class="row justify-content-center last-card-margin ">
    <div class="col-8">
      <%= render 'shared/errors', obj: @article %>
      <div class="row justify-content-center">
        <div class="col-10">
          <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
            <div class="form-group row">
              <%= f.label :title, class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
              </div>
            </div>
            <div class="form-group row">
              <%= f.label :description, class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
              </div>
            </div>
            <%# to create category %>
            <div class="form-group row">
              <%= f.label :category, class: "col-2 col-form-label text-light" %>
              <div class="col-10 shadow rounded p-2 m-2 mx-auto ">
                <%# <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
                <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                  <% cb.label(class: "checkbox-inline input_checkbox mr-2 text-white") {cb.check_box(class: "checkbox") + cb.text } %>
                <% end %>
              </div>
            </div>
            <div class="form-group row justify-content-center">
              <%= f.submit class: "btn btn-outline-light btn-lg" %>
            </div>
          <% end %>
        </div>
        <div class="mb-3">
          <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
        </div>
      </div>
    </div>
  </div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"> <strong> <%= @article.title %> </strong> </h2>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          created by:  <strong><%= @article.user.username  %></strong>
          , Id: <%= @article.id  %>
          <%# showing categories %>
          <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?)  %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end  %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
      <div class="mb-3 text-center">
        <%= link_to '[ Return to articles list ]', articles_path, class: "text-info" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/update.html.erb
<h1>updated the list </h1>
<%= @data_received  %>