config/routes.rb
Rails.application.routes.draw do
  get "pages/about"
  get "pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"
  get "about", to: "pages#about"
  resources :articles

  get "signup", to: "users#new"
  resources :users, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer class="py-4 mt-4 bg-dark text-white footer fixed-bottom">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "Pank", "https://github.com/pankaj485", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<%# showing flash messages if entries are saved from articles_controller.rb > create method  %>
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger"   %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler bg-light " type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link"  %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in?  %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end  %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in?  %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin  %>   Profile [<%= current_user.username  %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete Profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure you want to delete your account? "} %>
          </div>
        </li>
      <% end  %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= "Category"   %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if  logged_in? && current_user.admin  %>
            <%= link_to "Create category", new_category_path, class: "dropdown-item" %>
          <% end  %>
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in?  %>
        <li class="nav-item">
          <%= link_to "Log Out", logout_path, method: :delete, class:"nav-link"  %>
        </li>
      <% else  %>
        <li class="nav-item">
          <%= link_to "Log In", login_path, class:"nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", signup_path, class:"nav-link"  %>
        </li>
      <% end  %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="d-flex flex-column min-vh-100" >
    <%= render "layouts/navigation"  %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>